### ISSUE TITLE
feature request maintain scroll position on some/all pages

### ISSUE THREAD

**Issue by mat-0** [TabCarousel/TabCarousel#26]
My main use of this app is on a chromebook as an additional display, It's short screen height means some content i want to keep an eye on is below the fold. 

Can positions be accessed from the dom before app is activated?
- i.e. scroll to position after page load.
- or maintain position on pages that don't reload as per settings / requests.

thanks

**Comment by benjaminoakes** [comment]
Seems like something that could be done.  I'd accept a pull request for this.
