### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by benjaminoakes** [TabCarousel/TabCarousel#55]
> A Chrome extension to help you keep tabs on info you want to monitor. It's great for cycling through tabs on an external display, like a TV.
> 
> Authors: Benjamin Oakes and Madhur Ahuja
> 
> Tutorial
> 
> TabCarousel is simple: open tabs you want to monitor throughout the day, then click the toolbar icon. To stop, click the icon again.
> 
> By default, TabCarousel will flip through your tabs every 15 s, reloading them every 5 min. It's great on a unused display or TV. Put Chrome in full-screen mode (F11, or cmd-shift-f on the Mac) and let it go.
> 
> If you want to change how often TabCarousel flips through your tabs, right click on the toolbar icon and choose "Options".
> 
> New in 1.0.0 (2023-12-26):
> 
> * Manifest v3 support (Thank you, Madhur Ahuja!)
> 
> New in 0.5.4 (2020-05-14):
> 
> * Reduce permissions for Chrome Web Store policies
> 
> New in 0.5.3 (2012-08-21):
> 
> * Bug fixes
> 
> New in 0.5.2 (2011-07-06):
> 
> * Added an option to start Carousel automatically, by request from a user
> * Tabs that have previously failed to reload now reload correctly
> * Carousel now only flips through tabs in the window in which it was started
> 
> Example Uses
> 
> On a computer that has an external display (like an HDTV), try opening:
> 
> * NewRelic - Open as many tabs as you want for your apps -- don't forget to turn on "kiosk mode"
> * Twitter - Make a list of services you use, for example, and open it
> * Status sites:
>     * GitHub
>     * Heroku
> * Monitor your CI service
> * Packages with tracking information
> * Anything else that's on the web that you want to monitor
> 
> The TabCarousel wiki on GitHub has more: https://github.com/TabCarousel/TabCarousel/wiki
> 
> TabCarousel is open source software.  Contributions are welcome, as are suggestions and bug reports.  Check the project out at https://github.com/TabCarousel/TabCarousel

**Comment by benjaminoakes** [comment]
To release, we need to provide justification for "storage" and "activeTab."  I don't think this has been necessary in previous releases.

![Screenshot from 2023-12-26 14-45-14](https://github.com/TabCarousel/TabCarousel/assets/5323/f451cbb4-8a09-48a8-9bd2-27bf915a1b63)


@madhur Would you be able to provide justifications, please?

> **Permission justification**
>
> A [permission](https://developer.chrome.com/extensions/declare_permissions) is either one of a list of known strings, such as "activeTab", or a [match pattern](https://developer.chrome.com/extensions/match_patterns) giving access to one or more hosts.
Remove any permission that is not needed to fulfill the single purpose of your extension. Requesting an unnecessary permission will result in this version being rejected.


![Screenshot from 2023-12-26 14-41-22](https://github.com/TabCarousel/TabCarousel/assets/5323/44b89d33-cf6f-4a79-b5ec-c902c9c9c24e)

**Comment by madhur** [comment]
Hi @benjaminoakes , Here are the justifications:

We use `storage` to store following user preferences:

* `Flip wait Time` - The time it takes to switch to next tab
* `Automatic Start` - Weather it starts automatically or not


We use `activeTab` to display short once time tutorial in a new tab on how to use the extension, when the extension is installed.

**Comment by benjaminoakes** [comment]
Thanks! Will submit for review in the near future.

**Comment by benjaminoakes** [comment]
This is on my radar and I'm hoping to get to it soon.  My apologies, as this year has had many unexpected surprises.

**Comment by madhur** [comment]
Sure @benjaminoakes . No worries.

**Comment by madhur** [comment]
> Starting on June 3 on the Chrome Beta, Dev and Canary channels, if users still have Manifest V2 extensions installed, some will start to see a warning banner when visiting their extension management page - chrome://extensions - informing them that some (Manifest V2) extensions they have installed will soon no longer be supported. At the same time, extensions with the Featured badge that are still using Manifest V2 will lose their badge.

https://blog.chromium.org/2024/05/manifest-v2-phase-out-begins.html

**Comment by benjaminoakes** [comment]
![Screenshot from 2024-05-31 14-57-06](https://github.com/TabCarousel/TabCarousel/assets/5323/49eb84f4-7455-4d6c-8bbe-ccb50b75f553)


> **Your extension was submitted for review**
> You may check the status on the developer dashboard home page.
> Items staged to be published later will expire 30 days after they have passed review.

It also stated that review may take several weeks, though I hope it doesn't in our case.

The 1.0.0 update is now pending review.

![Screenshot from 2024-05-31 14-58-57](https://github.com/TabCarousel/TabCarousel/assets/5323/83cb15c5-d86b-4e56-9326-7168699facbc)

Thank you again @madhur for all your hard work on this!  I'm glad it's finally being released.  Thank you again for your patience.

**Comment by madhur** [comment]
Thats good to know. Thanks @benjaminoakes

**Comment by madhur** [comment]
> Great work both! Looks like this was approved today; Chrome web store page says `Updated June 3, 2024`.
> 
> Can you tag the release so we can see what's included, please?

@Jimadine  There are no functional changes. Its a mandatory manifest upgrade.

**Comment by Jimadine** [comment]
@madhur - probably worth tagging anyway, as all previous releases are?

![image](https://github.com/TabCarousel/TabCarousel/assets/7747515/99c1b423-4d72-4d4f-b09f-08b2e73992fc)

**Comment by Jimadine** [comment]
> Makes sense, Done. https://github.com/TabCarousel/TabCarousel/releases/tag/v1.0.0

Thanks for doing that, but when I browse the `v1.0.0` tag, it includes reasonably recent commits that (presumably) weren't packaged in the latest Chrome web store release (the 'Overview' field states `New in 1.0.0 (2023-12-26):`). Judging by the date, I think `v1.0.0` needs to tag commit 83a8d66dd11069bef254046ca5e5344e9835059f  - perhaps @benjaminoakes can confirm?

**Comment by benjaminoakes** [comment]
Without looking deeply, I would imagine @madhur would know better than I would

**Comment by madhur** [comment]
@Jimadine We have released v1.0.1 https://github.com/TabCarousel/TabCarousel/releases/tag/v1.0.1 . This should contain all recent commits. Also #58 is also released. It would be great if you can verify and close.

**Comment by benjaminoakes** [comment]
Closing this issue as v1.0.0 has been released.

Ideally, any other discussions can be handled on new issues.
