### ISSUE TITLE
When reloading tabs, bypass cache

### ISSUE THREAD

**Issue by Jimadine** [TabCarousel/TabCarousel#56]
We are using this extension for rudimentary digital signage. Some of the pages that occupy the tabs are Google Drive images that need a full CTRL+F5 reload in order for changes to reflect. It looks like the extension currently [does a normal reload](https://github.com/TabCarousel/TabCarousel/blob/83a8d66dd11069bef254046ca5e5344e9835059f/src/javascripts/background.js#L58). In order to do a full CTRL+F5 -style reload, `bypassCache` needs to be set to `true`, in the `reloadProperties` ([Link to documentation](https://developer.chrome.com/docs/extensions/reference/api/tabs#method-reload)).

Is this something that's of wider interest? Is there any detriment to changing the code to bypass the cache, or would it be better to make it a user-settable option?

**Comment by Jimadine** [comment]
Thank you. Yes implementing as an option sounds sensible.

**Comment by benjaminoakes** [comment]
Pull requests would be welcome for this feature 🙂

**Comment by madhur** [comment]
Raised #58

**Comment by madhur** [comment]
@Jimadine  Pls check in latest version and close.
