### ISSUE TITLE
1.0.1: tabs not carouselling when higher Flip Wait values set

### ISSUE THREAD

**Issue by Jimadine** [TabCarousel/TabCarousel#66]
I suspect this relates to closed issue https://github.com/TabCarousel/TabCarousel/issues/63

In my environment, version `1.0.1` is deployed as simple digital signage, but doesn't appear to be carouselling reliably. If I leave `Flip Wait (ms)` set to the default of `15000` everything works normally, however, we want to flip at `60000` (1 minute). Changes to this option appear to need a browser restart to take effect, but even after doing this, with flip set to `60000`, the extension does not flip to the next tab at this interval.

From a quick round of testing, it appears values greater than `30000` trigger the problem.

My test environment is Windows 10 22H2, Chromium 125.0.6422.142 (Official Build) (64-bit), where I can reproduce this. I also have `Start automatically` enabled.

It looks like `setTimeout` [is still used](https://github.com/TabCarousel/TabCarousel/blob/b5faf79ed2af826e2a3ed9bd8b8c8dcd62013357/src/javascripts/background.js#L86) - I'm wondering whether this has something to do with it?

From https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers#convert-timers
> It's common to use delayed or periodic operations using the setTimeout() or setInterval() methods. These APIs can fail in service workers, though, because the timers are canceled whenever the service worker is terminated.

**Comment by benjaminoakes** [comment]
Hi @Jimadine!

Thank you for reporting this.  The amount of technical detail you have included is especially helpful!

This does seem related to the recent required changes for Manifest v3, and your intuition about `setTimeout` makes sense to me.

Given the amount of technical knowledge you have (I noticed [Jimadine/chromeextension-digitalsignage-autoreloadtabs](https://github.com/Jimadine/chromeextension-digitalsignage-autoreloadtabs) on your profile :smiley:), I wonder: would you be interested in attempting a fix on TabCarousel?  We would be very grateful for any contributions you could make.

Other timer APIs would be a good option to consider.  We could also consider using `setTimeout` with a shorter time in combination with manual bookkeeping (e.g., decrement a counter in `localStorage`).  The approach is ultimately the decision of whoever implements the fix.  :slightly_smiling_face: 

Thanks again for this bug report and take care.  :wave:

**Comment by Jimadine** [comment]
Hi @benjaminoakes 

> Given the amount of technical knowledge you have (I noticed [Jimadine/chromeextension-digitalsignage-autoreloadtabs](https://github.com/Jimadine/chromeextension-digitalsignage-autoreloadtabs) on your profile 😃), I wonder: would you be interested in attempting a fix on TabCarousel? We would be very grateful for any contributions you could make.

I can certainly give it a go! My Javascript skills are a bit rusty, as I'm no longer doing much web development, but I am willing to try. I'll report back soon :smile:

**Comment by benjaminoakes** [comment]
> I've had a look and it's definitely the service worker becoming inactive that's triggering the problem. Googling around, there are various references to the service worker becoming inactive after 30 seconds, which fits with the problem behaviour.

Thanks for taking a look!  You definitely had good intuition!  :smile:

> [A very simple fix](https://stackoverflow.com/a/76544162/1754517) I've tested is to add `setInterval(()=>{self.serviceWorker.postMessage('test')},20000)` to the top of `background.js` to persist the service worker. There are other options on that [SO page](https://stackoverflow.com/questions/66618136/persistent-service-worker-in-chrome-extension), and using the offscreen API also works, though this requires extra files and the `offscreen` permission.

It may be best to avoid requesting (and having to [justify](https://github.com/TabCarousel/TabCarousel/issues/55#issuecomment-1869764291)) more permissions.

> I also had a look at [the Alarms API](https://developer.chrome.com/docs/extensions/reference/api/alarms) and the minimum alarm interval is 30 seconds, so I don't think we can straight replace `setTimeout` due to this constraint. I guess one could add some logic to use `setTimeout` for flipWait values `<= 30`, else `chrome.alarms`, but things could easily become messy.

That makes sense to me.  I defer to your judgment as to what option is best for our use case.  Thanks for doing so much research!

> As an aside: I followed the instructions in `CONTRIBUTING.md` but there was a bit more to do before TabCarousel "unpacked" would work without errors. There are several files that contain file path references which are valid for the minified package but not for the repo's `src` folder. One example: `manifest.json` - I had to change the `service_worker` property value from `background.min.js` to `javascripts/background.js`. I'm thinking the source code should reference the latter, and changes to file paths should be made as part of [the release process](https://github.com/TabCarousel/TabCarousel/wiki/Release-Process)? i.e. so one can hit the ground running after cloning the repo.

It seems `CONTRIBUTING.md` needs some TLC.  It may make sense to move it to the wiki.

Recently, I haven't been contributing much code, but I have been releasing this extension since @madhur rewrote it for Manifest v3.  I have run into some of the same issues you noted.  I'm glad you found [my notes](https://github.com/TabCarousel/TabCarousel/wiki/Release-Process) on how to release helpful.  It may be simpler if there was no build step, but I defer to @madhur as to what's best.  (Thank you again for your contributions @madhur!)

Is any of this aside a blocker for fixing the "> 30s" bug?  Should we discuss this more here or move it to a new issue?

**Comment by benjaminoakes** [comment]
I have [moved](https://github.com/TabCarousel/TabCarousel/commit/e3307f38010b849bae1602e66b4d5ee83e63a0b2) `CONTRIBUTING.md` to [the "Contributing" wiki page](https://github.com/TabCarousel/TabCarousel/wiki/Contributing) to facilitate updates.

**Comment by benjaminoakes** [comment]
I have updated [the "Contributing" wiki page](https://github.com/TabCarousel/TabCarousel/wiki/Contributing) to better reflect the state of things in 2024.  (This is the first substantial update to "Contributing" since 2011!)  Please feel free to update it if you'd like.  :smile: 

Hope this helps!

**Comment by benjaminoakes** [comment]
Thanks so much, @Jimadine!

It looks like you have things well in hand, but I'll continue to monitor
this issue in case something comes up. 🙂

**Comment by benjaminoakes** [comment]
This has been fixed in the newest release (v1.0.2).  Confirmation from other users is welcome. Please comment here if you have an opportunity to test the fix. (Thank you for your help!)
