### ISSUE TITLE
Image errors when testing 1.0.2 on develop

### ISSUE THREAD

**Issue by benjaminoakes** [TabCarousel/TabCarousel#75]
I receive these errors when choosing "load unpacked" on `dist/` after running `npm install` and `npx gulp`.

> Uncaught (in promise) Error: Failed to set icon 'images/icon_32_exp_1.75_stop_emblem.png': The source image could not be decoded.
> Uncaught (in promise) Error: Failed to set icon 'images/icon_32.png': The source image could not be decoded.
> Context
> extensions::setIcon

This used to complete successfully.  I've confirmed that the images are not loading in an image viewer.

This is blocking the release of v1.0.2.

**Comment by benjaminoakes** [comment]
@Jimadine Could you try the above steps on your side, please?  Do you run into the same problem? Any thoughts on what might be going on?

Related: resolving https://github.com/TabCarousel/TabCarousel/issues/71 may solve #75 (this issue) because there would no longer be a build step.

**Comment by Jimadine** [comment]
I've just run through the steps, and am seeing the same error after loading the unpacked extension. I will investigate.

**Comment by Jimadine** [comment]
The `dist` images are different file sizes and content to the `src` images, and not openable in e.g. Paint.NET. 

I've tried adding `,{ encoding: false, buffer: true, removeBOM: false}` to line 21 of `Gulpfile.js`, as recommended on various GitHub issue pages, but it doesn't solve the problem.

There's probably a way to solve this, but in the interests of getting `1.0.2` released, maybe worth just manually replacing the images in the zip file with the originals?

**Comment by Jimadine** [comment]
Oh silly me! I edited `Gulpfile.js` in my fork's directory then was trying to build in your repo directory. Merely adding `,{ encoding: false}` to line 21 does indeed fix it. Sounds like it relates to [Gulp version 5](https://medium.com/gulpjs/announcing-gulp-v5-c67d077dbdb7#:~:text=Stream%20encoding,your%20gulp%20streams.). Hopefully changing encoding to false won't have any unexpected side effects. I'll submit a PR.

**Comment by benjaminoakes** [comment]
Confirmed resolved when releasing v1.0.2 (#73)

Thanks!
